version: "3.9"

services:

  backend:
    build: ./backend
    container_name: aws-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

  frontend:
    build: .
    container_name: aws-frontend

    environment:
      - VITE_API_PROXY_TARGET=http://backend:5000

    ports:
      - "5173:5173"

    depends_on:
      - backend